/* CVS $Id: $ */
package org.w3id.scholarlydata.clodg.dogfood; 
import com.hp.hpl.jena.rdf.model.Model;
import com.hp.hpl.jena.rdf.model.ModelFactory;
import com.hp.hpl.jena.rdf.model.Property;
import com.hp.hpl.jena.rdf.model.Resource;
 
/**
 * Vocabulary definitions from ontologies/swc_2009-05-09.rdf 
 * @author Auto-generated by schemagen on 27 Apr 2016 19:29 
 */
public class SWC {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://data.semanticweb.org/ns/swc/ontology#";
    
    public static final String RESOURCE_NS = "http://data.semanticweb.org/";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>&lt;p&gt;Instead of this property, use the &lt;a href="#Delegate"&gt;Delegate&lt;/a&gt; 
     *  role.&lt;/p&gt;</p>
     */
    public static final Property attendeeAt = m_model.createProperty( "http://data.semanticweb.org/ns/swc/ontology#attendeeAt" );
    
    /** <p>&lt;p&gt;Deprecated because it has never been used and in order to reduce 
     *  the inflation of ontology terms.&lt;/p&gt;</p>
     */
    public static final Property biblioReference = m_model.createProperty( "http://data.semanticweb.org/ns/swc/ontology#biblioReference" );
    
    /** <p>&lt;p&gt;The call classes have been deprecated in SWC. Instead, we suggest 
     *  to use the &lt;a href="http://sw.deri.org/2005/08/conf/cfp"&gt;CfP ontology&lt;/a&gt;.&lt;/p&gt;</p>
     */
    public static final Property forEvent = m_model.createProperty( "http://data.semanticweb.org/ns/swc/ontology#forEvent" );
    
    /** <p>&lt;p&gt;Instead of this property, use the &lt;a href="#Delegate"&gt;Delegate&lt;/a&gt; 
     *  role.&lt;/p&gt;</p>
     */
    public static final Property hasAttendee = m_model.createProperty( "http://data.semanticweb.org/ns/swc/ontology#hasAttendee" );
    
    /** <p>&lt;p&gt;The call classes have been deprecated in SWC. Instead, we suggest 
     *  to use the &lt;a href="http://sw.deri.org/2005/08/conf/cfp"&gt;CfP ontology&lt;/a&gt;.&lt;/p&gt;</p>
     */
    public static final Property hasCall = m_model.createProperty( "http://data.semanticweb.org/ns/swc/ontology#hasCall" );
    
    /** <p>&lt;p&gt;The call classes have been deprecated in SWC. Instead, we suggest 
     *  to use the &lt;a href="http://sw.deri.org/2005/08/conf/cfp"&gt;CfP ontology&lt;/a&gt;.&lt;/p&gt;</p>
     */
    public static final Property hasCameraReadyDeadline = m_model.createProperty( "http://data.semanticweb.org/ns/swc/ontology#hasCameraReadyDeadline" );
    
    /** <p>&lt;p&gt;Deprecated because it has never been used and in order to reduce 
     *  the inflation of ontology terms.&lt;/p&gt;</p>
     */
    public static final Property hasCostAmount = m_model.createProperty( "http://data.semanticweb.org/ns/swc/ontology#hasCostAmount" );
    
    /** <p>&lt;p&gt;Deprecated because it has never been used and in order to reduce 
     *  the inflation of ontology terms.&lt;/p&gt;</p>
     */
    public static final Property hasCostCurrency = m_model.createProperty( "http://data.semanticweb.org/ns/swc/ontology#hasCostCurrency" );
    
    /** <p>&lt;p&gt; Relates an event such as a conference or any sub-event thereof to 
     *  a location where it takes place. &lt;/p&gt;</p>
     */
    public static final Property hasLocation = m_model.createProperty( "http://data.semanticweb.org/ns/swc/ontology#hasLocation" );
    
    /** <p>&lt;p&gt;Deprecated because it has never been used and in order to reduce 
     *  the inflation of ontology terms.&lt;/p&gt;</p>
     */
    public static final Property hasMenu = m_model.createProperty( "http://data.semanticweb.org/ns/swc/ontology#hasMenu" );
    
    /** <p>&lt;p&gt;The call classes have been deprecated in SWC. Instead, we suggest 
     *  to use the &lt;a href="http://sw.deri.org/2005/08/conf/cfp"&gt;CfP ontology&lt;/a&gt;.&lt;/p&gt;</p>
     */
    public static final Property hasNotificationDeadline = m_model.createProperty( "http://data.semanticweb.org/ns/swc/ontology#hasNotificationDeadline" );
    
    /** <p>&lt;p&gt; A generic property to model part-of relationships. In SWC this property 
     *  is used to relate a &lt;a href="#Proceedings"&gt;proceedings document&lt;/a&gt; 
     *  to the papers and articles contained in it. &lt;/p&gt;</p>
     */
    public static final Property hasPart = m_model.createProperty( "http://data.semanticweb.org/ns/swc/ontology#hasPart" );
    
    /** <p>&lt;p&gt; Relates an event such as a conference to its &lt;a href="#Programme"&gt;Programme&lt;/a&gt;. 
     *  &lt;/p&gt;</p>
     */
    public static final Property hasProgramme = m_model.createProperty( "http://data.semanticweb.org/ns/swc/ontology#hasProgramme" );
    
    /** <p>&lt;p&gt; Relates an &lt;a href="#AcademicEvent"&gt;event&lt;/a&gt; such as 
     *  a conference, workshop, etc. to a physical &lt;a href="#Artefact"&gt;artefact&lt;/a&gt;. 
     *  &lt;/p&gt;</p>
     */
    public static final Property hasRelatedArtefact = m_model.createProperty( "http://data.semanticweb.org/ns/swc/ontology#hasRelatedArtefact" );
    
    /** <p>&lt;p&gt; Relates an &lt;a href="#AcademicEvent"&gt;event&lt;/a&gt; such as 
     *  a conference, workshop, etc. to a &lt;a href="#ArgumentativeDocument"&gt;document&lt;/a&gt;. 
     *  &lt;/p&gt;</p>
     */
    public static final Property hasRelatedDocument = m_model.createProperty( "http://data.semanticweb.org/ns/swc/ontology#hasRelatedDocument" );
    
    /** <p>&lt;p&gt; Part of the &lt;a href="#Role"&gt;role&lt;/a&gt; modelling machinery 
     *  of SWC. This property relates an event (e.g. a conference) to a role at the 
     *  event (e.g. a conference chair). &lt;/p&gt;</p>
     */
    public static final Property hasRole = m_model.createProperty( "http://data.semanticweb.org/ns/swc/ontology#hasRole" );
    
    /** <p>&lt;p&gt;Deprecated because it has never been used and in order to reduce 
     *  the inflation of ontology terms.&lt;/p&gt;</p>
     */
    public static final Property hasSponsorship = m_model.createProperty( "http://data.semanticweb.org/ns/swc/ontology#hasSponsorship" );
    
    /** <p>&lt;p&gt;The call classes have been deprecated in SWC. Instead, we suggest 
     *  to use the &lt;a href="http://sw.deri.org/2005/08/conf/cfp"&gt;CfP ontology&lt;/a&gt;.&lt;/p&gt;</p>
     */
    public static final Property hasSubmissionDeadline = m_model.createProperty( "http://data.semanticweb.org/ns/swc/ontology#hasSubmissionDeadline" );
    
    /** <p>&lt;p&gt;The call classes have been deprecated in SWC. Instead, we suggest 
     *  to use the &lt;a href="http://sw.deri.org/2005/08/conf/cfp"&gt;CfP ontology&lt;/a&gt;.&lt;/p&gt;</p>
     */
    public static final Property hasSubmissionInstructions = m_model.createProperty( "http://data.semanticweb.org/ns/swc/ontology#hasSubmissionInstructions" );
    
    /** <p>&lt;p&gt;Instead of this property, use &lt;a href="http://xmlns.com/foaf/0.1/topic"&gt;foaf:topic&lt;/a&gt;.&lt;/p&gt;</p> */
    public static final Property hasTopic = m_model.createProperty( "http://data.semanticweb.org/ns/swc/ontology#hasTopic" );
    
    /** <p>&lt;p&gt; Part of the &lt;a href="#Role"&gt;role&lt;/a&gt; modelling machinery 
     *  of SWC. This property relates a role at an event (e.g. a conference chair) 
     *  to the person who actually holds the role. &lt;/p&gt;</p>
     */
    public static final Property heldBy = m_model.createProperty( "http://data.semanticweb.org/ns/swc/ontology#heldBy" );
    
    /** <p>&lt;p&gt; Part of the &lt;a href="#Role"&gt;role&lt;/a&gt; modelling machinery 
     *  of SWC. This property relates a person to the role (e.g. a conference chair) 
     *  it holds at an event. &lt;/p&gt;</p>
     */
    public static final Property holdsRole = m_model.createProperty( "http://data.semanticweb.org/ns/swc/ontology#holdsRole" );
    
    /** <p>&lt;p&gt; Relates a location to a conference or sub-event thereof which takes 
     *  place at it. &lt;/p&gt;</p>
     */
    public static final Property isLocationFor = m_model.createProperty( "http://data.semanticweb.org/ns/swc/ontology#isLocationFor" );
    
    /** <p>&lt;p&gt; A generic property to model part-of relationships. In SWC this property 
     *  is used to relate papers or articles to the &lt;a href="#Proceedings"&gt;proceedings 
     *  document&lt;/a&gt; in which they are contained. &lt;/p&gt;</p>
     */
    public static final Property isPartOf = m_model.createProperty( "http://data.semanticweb.org/ns/swc/ontology#isPartOf" );
    
    /** <p>&lt;p&gt;Deprecated because it has never been used and in order to reduce 
     *  the inflation of ontology terms.&lt;/p&gt;</p>
     */
    public static final Property isProvidedBy = m_model.createProperty( "http://data.semanticweb.org/ns/swc/ontology#isProvidedBy" );
    
    /** <p>&lt;p&gt;Deprecated because it has never been used and in order to reduce 
     *  the inflation of ontology terms.&lt;/p&gt;</p>
     */
    public static final Property isProviderOf = m_model.createProperty( "http://data.semanticweb.org/ns/swc/ontology#isProviderOf" );
    
    /** <p>&lt;p&gt; Part of the &lt;a href="#Role"&gt;role&lt;/a&gt; modelling machinery 
     *  of SWC. This property relates a role at an event (e.g. a conference chair) 
     *  to the event (e.g. a conference). &lt;/p&gt;</p>
     */
    public static final Property isRoleAt = m_model.createProperty( "http://data.semanticweb.org/ns/swc/ontology#isRoleAt" );
    
    /** <p>Events can be sub-events of other events. E.g., a talk can be a sub-event 
     *  of a session, which in turn can be a sub-event of a conference. The relation 
     *  is transitive - the talk is also a sub-event of the conference.</p>
     */
    public static final Property isSubEventOf = m_model.createProperty( "http://data.semanticweb.org/ns/swc/ontology#isSubEventOf" );
    
    /** <p>Events can be super-events of other events. E.g., a conference can be the 
     *  super-event of a session, which in turn can be the super-event of a talk. 
     *  The relation is transitive - the conference is also the super-event of the 
     *  talk.</p>
     */
    public static final Property isSuperEventOf = m_model.createProperty( "http://data.semanticweb.org/ns/swc/ontology#isSuperEventOf" );
    
    /** <p>&lt;p&gt;FOAF does not define an inverse of &lt;code&gt;foaf:member&lt;/code&gt;, 
     *  so SWC does it.&lt;/p&gt;</p>
     */
    public static final Property memberOf = m_model.createProperty( "http://data.semanticweb.org/ns/swc/ontology#memberOf" );
    
    /** <p>&lt;p&gt; A person might plan to attend a talk or session at a conference 
     *  or similar event. This property could be used to prepare a delegate's conference 
     *  experience with respect to who they want to meet, etc. &lt;/p&gt;</p>
     */
    public static final Property plansToAttend = m_model.createProperty( "http://data.semanticweb.org/ns/swc/ontology#plansToAttend" );
    
    /** <p>&lt;p&gt; Relates a &lt;a href="#ArgumentativeDocument"&gt;document&lt;/a&gt; 
     *  to an &lt;a href="#AcademicEvent"&gt;event&lt;/a&gt; such as a conference, 
     *  workshop, etc. &lt;/p&gt;</p>
     */
    public static final Property relatedToEvent = m_model.createProperty( "http://data.semanticweb.org/ns/swc/ontology#relatedToEvent" );
    
    /** <p>&lt;p&gt;Academic events are e.g. conferences and conference-like events, 
     *  and all the sub-events of those which are about the topic or theme of the 
     *  conference, such as talks or panels.&lt;/p&gt;</p>
     */
    public static final Resource AcademicEvent = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#AcademicEvent" );
    
    /** <p>&lt;p&gt; A hotel, hostel, BnB or similar. &lt;/p&gt;</p> */
    public static final Resource AccommodationPlace = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#AccommodationPlace" );
    
    public static final Resource AdditionalReviewer = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#AdditionalReviewer" );
    
    public static final Resource Administrator = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#Administrator" );
    
    /** <p>&lt;p&gt;An argumentative document is a document which uses analytical reasoning 
     *  and evidence in order to argue for a point of view. Typical examples are scientific 
     *  papers or political pamphlets. Negative examples are novels or plays (even 
     *  though a novel might also try to sway the reader to a certain point of view).&lt;/p&gt; 
     *  &lt;p&gt;According to &lt;a href="http://en.wikipedia.org/wiki/Text_types"&gt;Text 
     *  Types&lt;/a&gt;, an argumentative document is based "on the evaluation and 
     *  the subsequent subjective judgement in answer to a problem. It refers to the 
     *  reasons advanced for or against a matter".&lt;/p&gt;</p>
     */
    public static final Resource ArgumentativeDocument = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#ArgumentativeDocument" );
    
    /** <p>&lt;p&gt;&lt;emph&gt;Artefact&lt;/emph&gt; here means a document which can 
     *  have a physical manifestation, like a paper or the proceedings of a conference.&lt;/p&gt;</p>
     */
    public static final Resource Artefact = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#Artefact" );
    
    /** <p>&lt;p&gt; Any kind of break at the super-event, such as a coffee break. &lt;/p&gt;</p> */
    public static final Resource BreakEvent = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#BreakEvent" );
    
    /** <p>&lt;p&gt;The call classes have been deprecated in SWC. Instead, we suggest 
     *  to use the &lt;a href="http://sw.deri.org/2005/08/conf/cfp"&gt;CfP ontology&lt;/a&gt;.&lt;/p&gt; 
     *  &lt;p&gt;A &lt;emph&gt;call&lt;/emph&gt; is a public announcement, asking 
     *  for contribution of some kind to events such as conferences or workshops, 
     *  or to a publication such as a journal or book.&lt;/p&gt;</p>
     */
    public static final Resource Call = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#Call" );
    
    /** <p>&lt;p&gt;A call for demonstrations of software at a conference or workshop. 
     *  Submissions are usually in the form of extended abstracts (~2 page) discussing 
     *  the research questions addressed by the software and outlining the content 
     *  of the demonstration.&lt;/p&gt;</p>
     */
    public static final Resource CallForDemos = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#CallForDemos" );
    
    /** <p>&lt;p&gt;A &lt;emph&gt;call for papers&lt;/emph&gt; or &lt;emph&gt;CfP&lt;/emph&gt; 
     *  encourages authors to submit papers for peer-review for a conference or workshop, 
     *  or a journal or book.&lt;/p&gt;</p>
     */
    public static final Resource CallForPapers = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#CallForPapers" );
    
    /** <p>&lt;p&gt;This kind of call usually calls for potential delegates to attend 
     *  an event such as a conference or a workshop.&lt;/p&gt;</p>
     */
    public static final Resource CallForParticipation = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#CallForParticipation" );
    
    /** <p>&lt;p&gt;A call for scientific posters at a conference or workshop. Submissions 
     *  are usually in the form of extended abstracts (~2 page) discussing the research 
     *  presented on the poster.&lt;/p&gt;</p>
     */
    public static final Resource CallForPosters = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#CallForPosters" );
    
    /** <p>&lt;p&gt;A call which asks for contributions in the form of e.g. workshop 
     *  or tutorial proposals.&lt;/p&gt;</p>
     */
    public static final Resource CallForProposals = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#CallForProposals" );
    
    /** <p>&lt;p&gt; A sub-class of Role for various kinds of chair functions. Examples 
     *  are the main chair of a conference, the tutorials chair, the proceedings chair, 
     *  etc. Instead of introducing a large amount of sub-classes of Chair, we suggest 
     *  to model all the different chair functions as instances of Chair with appropriate 
     *  labels. &lt;/p&gt;</p>
     */
    public static final Resource Chair = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#Chair" );
    
    /** <p>Deprecating this - we can just use &lt;a href="#BreakEvent"&gt;BreakEvent&lt;/a&gt;.</p> */
    public static final Resource CoffeeBreak = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#CoffeeBreak" );
    
    /** <p>&lt;p&gt; A location at the &lt;a href="#ConferenceVenuePlace"&gt;conference 
     *  venue&lt;/a&gt; (or elsewhere), which is not a meeting room. &lt;/p&gt;</p>
     */
    public static final Resource CommunalPlace = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#CommunalPlace" );
    
    public static final Resource ConferenceChair = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#ConferenceChair" );
    
    /** <p>Deprecating this - we can just use &lt;a href="#TalkEvent"&gt;TalkEvent&lt;/a&gt;.</p> */
    public static final Resource ConferenceClosingEvent = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#ConferenceClosingEvent" );
    
    /** <p>Deprecating this - we can just use &lt;a href="#SocialEvent"&gt;SocialEvent&lt;/a&gt;.</p> */
    public static final Resource ConferenceDinner = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#ConferenceDinner" );
    
    /** <p>&lt;p&gt; A scientific conference. &lt;/p&gt; &lt;p&gt; TODO: Maybe this should 
     *  be opened up - why only scientific conferences? &lt;/p&gt;</p>
     */
    public static final Resource ConferenceEvent = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#ConferenceEvent" );
    
    /** <p>Deprecating this - we can just use &lt;a href="#TalkEvent"&gt;TalkEvent&lt;/a&gt;.</p> */
    public static final Resource ConferenceOpeningEvent = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#ConferenceOpeningEvent" );
    
    /** <p>&lt;p&gt; The location of a conference or conference-like event. Ideally, 
     *  this would be more specific than just the city. Instead it should be the hotel, 
     *  convention centre, university or similar place where the event is held. &lt;/p&gt;</p>
     */
    public static final Resource ConferenceVenuePlace = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#ConferenceVenuePlace" );
    
    /** <p>&lt;p&gt; A delegate is someone who attends a conference or conference-like 
     *  event. &lt;/p&gt;</p>
     */
    public static final Resource Delegate = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#Delegate" );
    
    /** <p>Deprecating this - we can just as well use &lt;a href="#TalkEvent"&gt;TalkEvent&lt;/a&gt;.</p> */
    public static final Resource DemoPresentation = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#DemoPresentation" );
    
    /** <p>Deprecating this - we can just as well use &lt;a href="#SessionEvent"&gt;SessionEvent&lt;/a&gt;.</p> */
    public static final Resource DemoSession = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#DemoSession" );
    
    /** <p>&lt;p&gt; Deprecating this, just use &lt;a href="#TrackChair"&gt;TrackChair&lt;/a&gt; 
     *  instead. &lt;/p&gt;</p>
     */
    public static final Resource DemosChair = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#DemosChair" );
    
    /** <p>A role that is only relevant in relation to the topic of the conference e.g. 
     *  Semantic Web Technologies Coordinator at a Semantic Web Conference.</p>
     */
    public static final Resource DogfoodTsar = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#DogfoodTsar" );
    
    /** <p>&lt;p&gt;Deprecated to reduce inflation of terms.&lt;/p&gt;</p> */
    public static final Resource DrinkingPlace = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#DrinkingPlace" );
    
    /** <p>&lt;p&gt;Deprecated to reduce inflation of terms.&lt;/p&gt;</p> */
    public static final Resource EatingPlace = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#EatingPlace" );
    
    /** <p>Deprecating this - we can just use &lt;a href="#SocialEvent"&gt;SocialEvent&lt;/a&gt;.</p> */
    public static final Resource Excursion = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#Excursion" );
    
    /** <p>&lt;p&gt; Deprecating this, just use &lt;a href="#TrackChair"&gt;TrackChair&lt;/a&gt; 
     *  instead. &lt;/p&gt;</p>
     */
    public static final Resource ExhibitionChair = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#ExhibitionChair" );
    
    /** <p>Deprecating this - we can just use &lt;a href="#BreakEvent"&gt;BreakEvent&lt;/a&gt;.</p> */
    public static final Resource FreeTimeBreak = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#FreeTimeBreak" );
    
    /** <p>Deprecating this - we can just as well use &lt;a href="#TalkEvent"&gt;TalkEvent&lt;/a&gt;.</p> */
    public static final Resource IndustrialTalk = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#IndustrialTalk" );
    
    /** <p>Deprecating this - we can just as well use &lt;a href="#TrackEvent"&gt;TrackEvent&lt;/a&gt;.</p> */
    public static final Resource IndustrialTrack = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#IndustrialTrack" );
    
    /** <p>&lt;p&gt; Deprecating this, just use &lt;a href="#TrackChair"&gt;TrackChair&lt;/a&gt; 
     *  instead. &lt;/p&gt;</p>
     */
    public static final Resource IndustryChair = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#IndustryChair" );
    
    /** <p>&lt;p&gt;As opposed to a peer-reviewed paper. This class has been deprecated 
     *  in order to reduce the inflation of classes.&lt;/p&gt;</p>
     */
    public static final Resource InvitedPaper = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#InvitedPaper" );
    
    /** <p>Deprecating this - we can just as well use &lt;a href="#TalkEvent"&gt;TalkEvent&lt;/a&gt;.</p> */
    public static final Resource KeynoteTalk = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#KeynoteTalk" );
    
    public static final Resource LocalOrganiser = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#LocalOrganiser" );
    
    /** <p>Deprecating this - we can just use &lt;a href="#BreakEvent"&gt;BreakEvent&lt;/a&gt;.</p> */
    public static final Resource MealBreak = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#MealBreak" );
    
    /** <p>&lt;p&gt; A lunch, dinner or similar event at a conference or conference-like 
     *  event. &lt;/p&gt;</p>
     */
    public static final Resource MealEvent = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#MealEvent" );
    
    /** <p>&lt;p&gt; A particular room at the &lt;a href="#ConferenceVenuePlace"&gt;conference 
     *  venue&lt;/a&gt; (or elsewhere). E.g., the room where a particular &lt;a href="#SessionEvent"&gt;SessionEvent&lt;/a&gt; 
     *  takes place. &lt;/p&gt;</p>
     */
    public static final Resource MeetingRoomPlace = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#MeetingRoomPlace" );
    
    /** <p>&lt;p&gt; In the context of SWC, a non-academic event is any kind or &lt;a 
     *  href="#OrganisedEvent"&gt;organised event&lt;/a&gt; which does not concern 
     *  the topic or theme of the conference as such. Examples are breaks, dinners, 
     *  parties, etc. &lt;/p&gt;</p>
     */
    public static final Resource NonAcademicEvent = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#NonAcademicEvent" );
    
    /** <p>&lt;p&gt;An event in time and space which is planned and organised, as opposed 
     *  to something which 'just happens', such as a car accident or sunset.&lt;/p&gt;</p>
     */
    public static final Resource OrganisedEvent = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#OrganisedEvent" );
    
    public static final Resource OrganisingCommitteeMember = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#OrganisingCommitteeMember" );
    
    /** <p>&lt;p&gt;A panel discussion at a conference or conference-like event, usually 
     *  involving several speakers.&lt;/p&gt;</p>
     */
    public static final Resource PanelEvent = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#PanelEvent" );
    
    /** <p>&lt;p&gt;A scientific/scholarly paper, e.g., an article in a scientific journal, 
     *  or a paper at a conference or workshop. A paper could also be unpublished 
     *  formally, as long as it has the form of a scientific paper (introduction, 
     *  conclusion, related work, etc.).&lt;/p&gt;</p>
     */
    public static final Resource Paper = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#Paper" );
    
    /** <p>Deprecating this - we can just as well use &lt;a href="#TalkEvent"&gt;TalkEvent&lt;/a&gt;.</p> */
    public static final Resource PaperPresentation = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#PaperPresentation" );
    
    /** <p>Deprecating this - we can just as well use &lt;a href="#SessionEvent"&gt;SessionEvent&lt;/a&gt;.</p> */
    public static final Resource PaperSession = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#PaperSession" );
    
    /** <p>&lt;p&gt; Deprecating this, just use &lt;a href="#TrackChair"&gt;TrackChair&lt;/a&gt; 
     *  instead. &lt;/p&gt;</p>
     */
    public static final Resource PhDSymposiumChair = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#PhDSymposiumChair" );
    
    /** <p>&lt;p&gt; Deprecated: no real need to have an internal super-class for locations, 
     *  we can just use the &lt;a href="&amp;geo;SpatialThing"&gt;SpatialThing&lt;/a&gt;. 
     *  &lt;/p&gt;</p>
     */
    public static final Resource Place = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#Place" );
    
    /** <p>&lt;p&gt;A scientific poster at a conference or workshop.&lt;/p&gt;</p> */
    public static final Resource Poster = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#Poster" );
    
    /** <p>Deprecating this - we can just as well use &lt;a href="#TalkEvent"&gt;TalkEvent&lt;/a&gt;.</p> */
    public static final Resource PosterPresentation = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#PosterPresentation" );
    
    /** <p>Deprecating this - we can just as well use &lt;a href="#SessionEvent"&gt;SessionEvent&lt;/a&gt;.</p> */
    public static final Resource PosterSession = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#PosterSession" );
    
    /** <p>&lt;p&gt; Deprecating this, just use &lt;a href="#TrackChair"&gt;TrackChair&lt;/a&gt; 
     *  instead. &lt;/p&gt;</p>
     */
    public static final Resource PostersChair = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#PostersChair" );
    
    /** <p>&lt;p&gt; A presenter is someone who presents matter in front of an audience. 
     *  Examples of events to which this role applies are paper presentations, tutorials, 
     *  or talks. A keynote speaker could also be modelled as an instance of this 
     *  class. &lt;/p&gt;</p>
     */
    public static final Resource Presenter = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#Presenter" );
    
    public static final Resource PrintedProceedingsChair = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#PrintedProceedingsChair" );
    
    /** <p>&lt;p&gt;The proceedings of a conference or workshop, which contain the papers 
     *  presented there.&lt;/p&gt;</p>
     */
    public static final Resource Proceedings = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#Proceedings" );
    
    /** <p>&lt;p&gt;A document containing the programme of an event such as a conference 
     *  or workshop. Typically, the programme would list the times and dates for the 
     *  individual sub-events, e.g., talks, dinners, panel discussions, etc.&lt;/p&gt;</p>
     */
    public static final Resource Programme = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#Programme" );
    
    public static final Resource ProgrammeChair = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#ProgrammeChair" );
    
    /** <p>&lt;p&gt; This role is played by the members of the programme committee of 
     *  a conference or conference-like event. We found this role to be so significant 
     *  that it justifies to be represented by its own class. &lt;/p&gt;</p>
     */
    public static final Resource ProgrammeCommitteeMember = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#ProgrammeCommitteeMember" );
    
    public static final Resource PublicityChair = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#PublicityChair" );
    
    /** <p>Deprecating this - we can just use &lt;a href="#SocialEvent"&gt;SocialEvent&lt;/a&gt;.</p> */
    public static final Resource Reception = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#Reception" );
    
    /** <p>Deprecating this - we can just as well use &lt;a href="#TrackEvent"&gt;TrackEvent&lt;/a&gt;.</p> */
    public static final Resource ResearchTrack = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#ResearchTrack" );
    
    /** <p>&lt;p&gt; Deprecating this, just use &lt;a href="#ProgrammeCommitteeMember"&gt;ProgrammeCommitteeMember&lt;/a&gt; 
     *  instead. &lt;/p&gt;</p>
     */
    public static final Resource Reviewer = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#Reviewer" );
    
    /** <p>&lt;p&gt; Role is the super-class of all the different roles performed at 
     *  a conference or workshop. Examples are the various conference chairs, the 
     *  delegates, presenters, PC members, etc. The intended use of this class is 
     *  that an instance of Role will be related to the event at which it is performed, 
     *  and to the person which performs it. &lt;/p&gt; &lt;p&gt; Since the set of 
     *  roles is slightly different for each event, and since it would therefore be 
     *  impossible to provide sub-classes for all needs and circumstances, the SWC 
     *  ontology only contains a very basic set of Role classes. Rather than diversifying 
     *  the set of Role classes to cater for all needs, users should instead instantiate 
     *  the small set of different Role classes and cover the roles at a specific 
     *  event in this way. E.g., instead of sub-classing the Chair role with MainChair, 
     *  WorkshopChair, TutorialChair, etc., the different kinds of chairs should simply 
     *  be instances of the generic Chair class and be labelled appropriately. &lt;/p&gt;</p>
     */
    public static final Resource Role = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#Role" );
    
    /** <p>&lt;p&gt; Deprecating this, just use &lt;a href="#TrackChair"&gt;TrackChair&lt;/a&gt; 
     *  instead. &lt;/p&gt;</p>
     */
    public static final Resource SWChallengeChair = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#SWChallengeChair" );
    
    public static final Resource SessionChair = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#SessionChair" );
    
    /** <p>&lt;p&gt; A session dedicated to a specific topic at a conference. This could 
     *  be a session with talks, or also a poster session, a demo session, or any 
     *  other kind of session. &lt;/p&gt;</p>
     */
    public static final Resource SessionEvent = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#SessionEvent" );
    
    /** <p>&lt;p&gt;A set of slides used for a presentation of e.g. a paper at a conference.&lt;/p&gt;</p> */
    public static final Resource SlideSet = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#SlideSet" );
    
    /** <p>&lt;p&gt; Examples for social events are parties or excursions. &lt;/p&gt;</p> */
    public static final Resource SocialEvent = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#SocialEvent" );
    
    /** <p>&lt;p&gt;Deprecated because it has never been used and in order to reduce 
     *  the inflation of ontology terms.&lt;/p&gt;</p>
     */
    public static final Resource Sponsorship = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#Sponsorship" );
    
    public static final Resource SponsorshipChair = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#SponsorshipChair" );
    
    public static final Resource SubmissionsChair = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#SubmissionsChair" );
    
    /** <p>&lt;p&gt;A type of paper which accompanies the demonstration of software, 
     *  also known as an extended abstract or demo description. This class has been 
     *  deprecated in order to reduce the inflation of classes; it is too specific 
     *  for CS conferences.&lt;/p&gt;</p>
     */
    public static final Resource SystemDemonstration = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#SystemDemonstration" );
    
    /** <p>&lt;p&gt; A type of paper which is mainly describes the properties, implementation 
     *  or architecture of an system (such as a software system). &lt;/p&gt; &lt;p&gt; 
     *  Deprecating this: it's too specific for, not generic enough to apply for most 
     *  conferences.</p>
     */
    public static final Resource SystemDescription = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#SystemDescription" );
    
    /** <p>&lt;p&gt; A speaker giving a talk. This could be the presentation of a paper, 
     *  but also keynote speech or any other kind of talk. &lt;/p&gt;</p>
     */
    public static final Resource TalkEvent = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#TalkEvent" );
    
    /** <p>&lt;p&gt; The chair of a particular track of a conference, responsible for 
     *  all submissions and actions regarding this track. &lt;/p&gt;</p>
     */
    public static final Resource TrackChair = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#TrackChair" );
    
    /** <p>&lt;p&gt; A track groups all those sessions or events at a conference or workshop 
     *  that belong to a common, overall theme. Depending on the conference, tracks 
     *  can be quite generic, such as "Research" or "Industrial", but can also be 
     *  more specific, such as "Semantic Web" or "Numismatics". SWC does not define 
     *  any specific tracks, since conferences often differ so much with respect to 
     *  how they structure their tracks, that it would be pointless to try and find 
     *  a set of tracks that would suit all conferences. &lt;/p&gt; &lt;p&gt;Sub-classes 
     *  of TrackEvent which were defined in previous versions of the SWC ontology 
     *  are now deprecated.&lt;/p&gt;</p>
     */
    public static final Resource TrackEvent = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#TrackEvent" );
    
    public static final Resource Treasurer = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#Treasurer" );
    
    public static final Resource Tutor = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#Tutor" );
    
    /** <p>&lt;p&gt; A tutorial is a special session at a conference or workshop, somewhat 
     *  like a long lecture on a specific topic. &lt;/p&gt;</p>
     */
    public static final Resource TutorialEvent = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#TutorialEvent" );
    
    public static final Resource TutorialOrganiser = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#TutorialOrganiser" );
    
    /** <p>&lt;p&gt; Deprecating this, just use &lt;a href="#Presenter"&gt;Presenter&lt;/a&gt; 
     *  instead. &lt;/p&gt;</p>
     */
    public static final Resource TutorialPresenter = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#TutorialPresenter" );
    
    public static final Resource TutorialsChair = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#TutorialsChair" );
    
    public static final Resource Webmaster = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#Webmaster" );
    
    /** <p>Deprecating this - we can just as well use &lt;a href="#TalkEvent"&gt;TalkEvent&lt;/a&gt;.</p> */
    public static final Resource WelcomeTalk = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#WelcomeTalk" );
    
    /** <p>&lt;p&gt; A scientific workshop. Workshops are often co-located with &lt;a 
     *  href="#ConferenceEvent"&gt;ConferenceEvent&lt;/a&gt;s. &lt;/p&gt;</p>
     */
    public static final Resource WorkshopEvent = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#WorkshopEvent" );
    
    public static final Resource WorkshopOrganiser = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#WorkshopOrganiser" );
    
    public static final Resource WorkshopsChair = m_model.createResource( "http://data.semanticweb.org/ns/swc/ontology#WorkshopsChair" );
    
}
